name: gitlab pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
            
      - name: Build Pre-processing
        run: |
          git clone https://github.com/CaiJimmy/hugo-theme-stack ./themes/hugo-theme-stack
          sed -i '1 c\baseurl: https://minggemg-sourcecode.gitlab.io/cloudflare-pages-blog' ./config.yaml
        
      - name: Build
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gl-pages  # default: gh-pages
